DELETE
FROM tag;

INSERT INTO tag (id, name)
VALUES (1, 'Celebration'),
       (2, 'Holiday'),
       (3, 'Mountain'),
       (4, 'Cruise'),
       (5, 'Cosmetics'),
       (6, 'City'),
       (7, 'Travel'),       
       (8, 'Yoga'),
       (9, 'Makeup'),
       (10, 'Beach'),
       (11, 'Vacation'),
       (12, 'Cocktails'),
       (13, 'Massage'),
       (14, 'Karaoke'),
       (15, 'Class'),
       (16, 'Family'),
       (17, 'Course'),
       (18, 'Belated'),
       (19, 'Co-Worker'),
       (20, 'Sympathy'),
       (21, 'Nutrition'),
       (22, 'Updated'),
       (23, 'Training'),
       (24, 'Health'),
       (25, 'Self-care'),
       (26, 'Anniversary'),
       (27, 'Fellow'),
       (28, 'Restaurant'),
       (29, 'Ballet'),
       (30, 'Feng shui'),
       (31, 'Souvenirs'),
       (32, 'Train'),
       (33, 'Bon apptit'),
       (34, 'Culture'),
       (35, 'Creative'),
       (36, 'grinder'),
       (37, 'Journey'),
       (38, 'yoga mat'),
       (39, 'Mother Day'),
       (40, 'Hauls'),
       (41, 'Delivery'),
       (42, 'Loungewear'),
       (43, 'Data science'),
       (44, 'Condolence'),
       (45, 'lululemon'),
       (46, 'planning'),
       (47, 'Energy'),
       (48, 'bedding'),
       (49, 'basics'),
       (50, 'Snowboarding'),
       (51, 'Eco-Friendly'),
       (52, 'Meditation'),
       (53, 'Biotechnology'),
       (54, 'Birthday'),
       (55, 'Strength training'),
       (56, 'Christmas'),
       (57, 'Well done!'),
       (58, 'Retirement'),
       (59, 'Road Trip'),
       (60, 'Seafood'),
       (61, 'Father''s Day'),
       (62, 'Just Married'),
       (63, 'Happy'),
       (64, 'Mindfulness'),
       (65, 'Photography class'),
       (66, 'Pilates'),
       (67, 'Charitable'),
       (68, 'Clothing'),
       (69, 'Birthdays'),
       (70, 'Cats'),
       (71, 'Sports'),
       (72, 'loves Goldbelly'),
       (73, 'Design'),
       (74, 'Pets'),
       (75, 'Baby Shower'),
       (76, 'Language class'),
       (77, 'Bon Voyage!'),
       (78, 'Modern'),
       (79, 'Environmental'),
       (80, 'Cardio'),
       (81, 'Concert'),
       (82, 'daily shopping'),
       (83, 'Gift'),
       (84, 'Eclectic'),
       (85, 'Kids'),
       (86, 'HappyDiwali!'),
       (87, 'Baby'),
       (88, 'Eco-tourism'),
       (89, 'Easter greetings!'),
       (90, 'necklaces'),
       (91, 'Photography'),
       (92, 'Groceries'),
       (93, 'Motivational'),
       (94, 'Vegetarian'),
       (95, 'Tarot'),
       (96, 'Coffee'),
       (97, 'Art of Shaving'),
       (98, 'Welcome'),
       (99, 'Oil and gas'),
       (100, 'Trip'),
       (101, 'Happy Birthday'),
       (102, 'Spoil yourself!'),
       (103, 'Manufacturing'),
       (104, 'Testimonials'),
       (105, 'Day'),
       (106, 'cord cutter'),
       (107, 'Headspace Subscription'),
       (108, 'Health care'),
       (109, 'Climate change'),
       (110, 'Newborn'),
       (111, 'Chocolate Factory'),
       (112, 'Show'),
       (113, 'magazines'),
       (114, 'Productivity'),
       (115, 'Spa Day'),
       (116, 'Movie Theater'),
       (117, 'Sweet Wine'),
       (118, 'loungewear'),
       (119, 'jeans'),
       (120, 'Barre'),
       (121, 'Triathlon'),
       (122, 'Whiskey'),
       (123, 'Personalized'),
       (124, 'Budget-Friendly'),
       (125, 'Friends'),
       (126, 'engagement ring'),
       (127, 'Bungee jumping'),
       (128, 'Wellness'),
       (129, 'Interior design'),
       (130, 'Festival'),
       (131, 'Ivy League'),
       (132, 'Beauty'),
       (133, 'Camping'),
       (134, 'Experiential'),
       (135, 'Pin It'),
       (136, 'Horoscopes'),
       (137, 'tech reviews'),
       (138, 'Adventure'),
       (139, 'Lesson'),
       (140, 'linen sheets'),
       (141, 'Thai cuisine'),
       (142, 'Customized'),
       (143, 'Astrology'),
       (144, 'Sales'),
       (145, 'bathrobe'),
       (146, 'Italian cuisine'),
       (147, 'Hoppy Easter!'),
       (148, 'Wildlife'),
       (149, 'Opera'),
       (150, 'Accessibility'),
       (151, 'BBQ'),
       (152, 'Telemedicine'),
       (153, 'Sunglasses'),
       (154, 'Spa'),
       (155, 'Brunch'),
       (156, 'pans'),
       (157, 'Skiing'),
       (158, 'Deepavali'),
       (159, 'wrap'),
       (160, 'City Break'),
       (161, 'Tech'),
       (162, 'housewarming'),
       (163, 'Eco-friendly'),
       (164, 'Gym'),
       (165, 'multiple experts'),
       (166, 'Adventure Holiday'),
       (167, 'Outdoor Adventure'),
       (168, 'Housewarming'),
       (169, 'Time management'),
       (170, 'mens pants'),
       (171, 'Renovation'),
       (172, 'TRX'),
       (173, 'Nature'),
       (174, 'Boho'),
       (175, 'Accessories'),
       (176, 'Cryptocurrency'),
       (177, 'Game Night'),
       (178, 'Rock climbing'),
       (179, 'Architecture'),
       (180, 'Evening'),
       (181, 'Ethical'),
       (182, 'Horseback riding'),
       (183, 'Wedding'),
       (184, 'Boxing'),
       (185, 'Con-GRAD-ulations!'),
       (186, 'Entrepreneurship'),
       (187, 'Flight'),
       (188, 'Fishing'),
       (189, 'Insurance'),
       (190, 'Lecture'),
       (191, 'Embroidered'),
       (192, 'meal delivery'),
       (193, 'Cooking class'),
       (194, 'Graphic design'),
       (195, 'Zip lining'),
       (196, 'Beach vacation'),
       (197, 'Pottery class'),
       (198, 'Knitting'),
       (199, 'Renewable energy'),(200, 'Crossfit'),
       (201, 'Sushi'),
       (202, 'Romantic Getaway'),
       (203, 'Innovative'),
       (204, 'Relaxation'),
       (205, 'Read Next'),
       (206, 'ever want'),
       (207, 'Martial arts'),
       (208, 'Hari Raya'),
       (209, 'Therapy'),
       (210, 'Cocktail party'),
       (211, 'Picnic'),
       (212, 'Warmest regards.'),
       (213, 'Hanukkah'),
       (214, 'Accounting'),
       (215, 'Health insurance'),
       (216, 'Home goods'),
       (217, 'Anniversary Celebration'),
       (218, 'Artificial intelligence'),
       (219, 'Foodie'),
       (220, 'Retreat'),
       (221, 'Breakfast'),
       (222, 'RockMusic'),
       (223, 'Downloads'),
       (224, 'Gradient puzzles'),
       (225, 'Medical devices'),
       (226, 'Get Well'),
       (227, 'Universal retailers'),
       (228, 'Apologies/I''m Sorry'),
       (229, 'Movie night'),
       (230, 'Weight loss'),
       (231, 'Handmade'),
       (232, 'Board game night'),
       (233, 'Scuba diving'),
       (234, 'Indoor Adventure'),
       (235, 'Tea'),
       (236, 'Toys'),
       (237, 'Pure Bliss Spa'),
       (238, 'Construction'),
       (239, 'Tour'),
       (240, 'Pedicure'),
       (241, 'Fitness'),
       (242, 'Im buying'),
       (243, 'vibrator'),
       (244, 'teens'),
       (245, 'Winc Subscription'),
       (246, 'Supply chain management'),
       (247, 'Forestry'),
       (248, 'Wine Lover''s'),
       (249, 'plant parent'),
       (250, 'Shopping'),
       (251, 'Home decor'),
       (252, 'Machine learning'),
       (253, 'Fashion design'),
       (254, 'Transportation'),
       (255, 'Craft beer'),
       (256, 'Dance'),
       (257, 'Thank You'),
       (258, 'Rustic'),
       (259, 'Workshop'),
       (260, 'Business anniversary'),
       (261, 'hard-to-shop-for teenager'),
       (262, 'Significant Other'),
       (263, 'Graduation'),
       (264, 'DIY'),
       (265, 'Organic'),
       (266, 'Running'),
       (267, 'Helicopter tour'),
       (268, 'Manicure'),
       (269, 'Crochet'),
       (270, 'Expedition'),
       (271, 'French cuisine'),
       (272, 'New Year''s'),
       (273, 'Self Pick-Up'),
       (274, 'Thank you'),
       (275, 'Be mine'),
       (276, 'Fashion'),
       (277, 'travel enthusiast'),
       (278, 'Relaxation techniques'),
       (279, 'College Student'),
       (280, 'Personal anniversary'),
       (281, 'Paleo'),
       (282, 'Wellness Holiday'),
       (283, 'Indulge, darling'),
       (284, 'Technology'),
       (285, 'Educational'),
       (286, 'Congratulations/Good Luck'),
       (287, 'Shave'),
       (288, 'Fragrance'),
       (289, 'cook'),
       (290, 'Fair trade'),
       (291, 'Hiking'),
       (292, 'Marketing'),
       (293, 'Boys'' Day Out'),
       (294, 'Legal'),
       (295, 'Friendship'),
       (296, 'Art'),
       (297, 'Quality management'),
       (298, 'Cultural'),
       (299, 'iPhone App'),
       (300, 'Body Shop'),
       (301, 'Artisan'),
       (302, 'Twitter'),
       (303, 'Tax preparation'),
       (304, 'Wine and cheese night'),
       (305, 'Leadership'),
       (306, 'Project management'),
       (307, 'Book Lover''s'),
       (308, 'Mexican cuisine'),
       (309, 'Home improvement'),
       (310, 'Mountain Retreat'),
       (311, 'Contemporary'),
       (312, 'Weekend'),
       (313, 'Comedy'),
       (314, 'teacher'),
       (315, 'Countryside Escape'),
       (316, 'Stand-up'),
       (317, 'Retro'),
       (318, 'Valentine''s Day'),
       (319, 'Engraved'),
       (320, 'Muscle building'),
       (321, 'Relaxing Holiday'),
       (322, 'Jewelry'),
       (323, 'Go wild!!'),
       (324, 'Investment'),
       (325, 'Movies'),
       (326, 'High tea'),
       (327, 'New Baby'),
       (328, 'sustainable'),
       (329, 'Music Lovers'),
       (330, 'Sewing'),
       (331, 'Cycling'),
       (332, 'Games'),
       (333, 'Chinese cuisine'),
       (334, 'Nice work!'),
       (335, 'Minimalist'),
       (336, 'Music'),
       (337, 'Coaching'),
       (338, 'Girls Day Out'),
       (339, 'iPad App'),
       (340, 'Books'),
       (341, 'Nail care'),
       (342, 'Management'),
       (343, 'Agriculture'),
       (344, 'Gluten-free'),
       (345, 'Surprise'),
       (346, 'Crafts'),
       (347, 'Gift yourself!'),
       (348, 'Honeymoon'),
       (349, 'Congratulatory'),
       (350, 'Indian cuisine'),
       (351, 'Surfing'),
       (352, 'Theater'),
       (353, 'Vintage'),
       (354, 'Happy Easter!'),
       (355, 'Couples'),
       (356, 'Haircare'),
       (357, 'Bootcamp'),
       (358, 'Solo Retreat'),
       (359, 'bath towels'),
       (360, 'Real estate'),
       (361, 'Away'),
       (362, 'Wine'),
       (363, 'Gardening'),
       (364, 'Social'),
       (365, 'Musical'),
       (366, 'Public relations'),
       (367, 'Sustainable'),
       (368, 'Inspiring'),
       (369, 'Escape'),
       (370, 'Logistics'),
       (371, 'Occasions'),
       (372, 'Traditional'),
       (373, 'Writing'),
       (374, 'Experience'),
       (375, 'Safari'),
       (376, 'Shoes'),
       (377, 'Software development'),
       (378, 'Getaway'),
       (379, 'Movie Night'),
       (380, 'New Home'),
       (381, 'Personal development'),
       (382, '(required)'),
       (383, 'Skydiving'),
       (384, 'Business coaching'),
       (385, 'Watches'),
       (386, 'Day Out'),
       (387, 'Tea time'),
       (388, 'accessories'),
       (389, 'Food'),
       (390, 'Advertising'),
       (391, 'Concerts'),
       (392, 'Customer service'),
       (393, 'Cookware'),
       (394, 'Bags'),
       (395, 'Glamping'),
       (396, 'Team building'),
       (397, 'Lunch'),
       (398, 'Travel Lover''s'),
       (399, 'Chocolate tasting'),
       (400, 'Keto'),
       (401, 'Dinner party'),
       (402, 'WhatsApp'),
       (403, 'Kitchen'),
       (404, 'Haircut'),
       (405, 'Performance'),
       (406, 'Classic'),
       (407, 'Engagement'),
       (408, 'Volunteer trip'),
       (409, 'Dinner'),
       (410, 'Tea Leaf'),
       (411, 'Painting class'),
       (412, 'Entertainment'),
       (413, 'Art Lover''s'),
       (414, 'Product design'),
       (415, 'Seminar'),
       (416, 'Blockchain'),
       (417, 'Coffee Bean'),
       (418, 'Vegan'),
       (419, 'Cosmetic'),
       (420, 'Web design'),
       (421, 'Neo Fashion'),
       (422, 'Responsible'),
       (423, 'Legal services'),
       (424, 'Skincare'),
       (425, 'Spa day'),
       (426, 'Conservation'),
       (427, 'Spiritual'),
       (428, 'Gadgets'),
       (429, 'Risk management'),
       (430, 'Excursion'),
       (431, 'Balloon ride'),
       (432, 'Date Night'),
       (433, 'Utilities'),
       (434, 'Mining'),
       (435, 'Jewelry design'),
       (436, 'Pharmaceuticals');
