###
POST http://localhost:8080/api/token/authenticate

###
POST http://localhost:8080/api/token/refresh

###
POST http://localhost:8080/api/token/register

###
GET http://localhost:8080/api/token/profile

###
POST http://localhost:8080/api/token/logout

###
POST http://localhost:8080/api/logout

###
POST http://localhost:8080/api/login